OUTPUT_DIR: "checkpoints/sun_4w_2s"
LOG_FILE_NAME: "ZSL.log"
MODEL_FILE_NAME: "best_model.pth"
MODEL:
  META_ARCHITECTURE: "ZSLModel"
  SCALE: 25.0
  ATTEN_THR: 9.
  BACKBONE:
    PRETRAINED: True
  ATTENTION:
    CHANNEL: 512
    WEIGHT_SHARED: True
    W2V_PATH: "datasets/Attribute/w2v"
  LOSS:
#    LAMBDA1: 0.5
#    LAMBDA2: 0.1
#    LAMBDA3: 0.2
    LAMBDA1: 1. #L_reg
    LAMBDA2: 1.
    LAMBDA3: 1.
    LAMBDA4: 0.001 #L_cls_att
    LAMBDA5: 0.001 #L_proto
    LAMBDA6: 0.001
    TEMP: 0.1
    MARGIN: 0.8
  RESUME_FROM: None

DATASETS:
  NAME: "SUN"
  IMAGE_SIZE: 224
  WAYS: 4
  SHOTS: 2

DATALOADER:
#  MODE: 'random'
  MODE: 'episode'
  N_BATCH: 300

SOLVER:
  MAX_EPOCH: 20
  BASE_LR: 1e-3
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
  GAMMA: 0.5
  STEPS: 10
  DATA_AUG: "resize_random_crop"

TEST:
  IMS_PER_BATCH: 100
  DATA_AUG: "resize_crop"
  GAMMA: 0.7